 [[cells]]
 name = "cota-type"
 enable_type_id = true
 location = { file = "build/release/cota-type" }

 # reference to on-chain cells
 [[cells]]
 name = "ckb_smt"
 enable_type_id = false
 location = { file = "build/release/ckb_smt" }
 

 # Dep group cells
 [[dep_groups]]
 name = "dep_group"
 cells = [
   "cota-type",
   "ckb_smt"
 ]

 # Replace with your own lock if you want to unlock deployed cells.
 # For example the secp256k1 lock
 [lock]
 code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
 args = "0x0000000000000000000000000000000000000000"
 hash_type = "type"

